### ISSUE TITLE
Using Enchantments through Polymer API removing level at the end (1.19)

### ISSUE THREAD

**Issue by firenh** [NucleoidMC/Server-Translations#33]
When using Server Translations API for enchantments through Polymer, the enchantment tooltip on items removes the level at the end.

Example: 
- Without Server Translations: `enchantment.enchanted_expanded.frost_aspect II`
- With Server Translations: `Frost Aspect` (`II` is missing)

Here's a link to the repo I used to test this, using Polymer and Server Translation API: https://github.com/firenh/enchanted_expanded

**Comment by Patbox** [comment]
Hey! Could you try updating to latest version, as it should fix some issues!

**Comment by firenh** [comment]
yeah that fixed it, thank you!!!
