### ISSUE TITLE
Suggestion: document adding ST API as dependency 

### ISSUE THREAD

**Issue by InFTord** [NucleoidMC/Server-Translations#46]
For me, using CurseMaven doesn't work.
Is there any documented way of adding Server Translations API to dependencies

**Comment by ashhhleyyy** [comment]
ServerTranslationsAPI is available on the Nucleoid maven repository https://maven.nucleoid.xyz as `fr.catcore:server-translations-api:VERSION`
You can see the list of versions here: https://maven.nucleoid.xyz/fr/catcore/server-translations-api/

**Comment by InFTord** [comment]
thanks! :)
