### ISSUE TITLE
Mistakenly tried to use 1.19.3 version on 1.20 server

### ISSUE THREAD

**Issue by RealKomander** [NucleoidMC/Server-Translations#53]
It broke cyrillic symbols
<img width="339" alt="image" src="https://github.com/NucleoidMC/Server-Translations/assets/124439290/b0de1df7-8ca8-4243-9a65-6f6cc519b3c8">

Didn't fix even after removing the mod

**Comment by Patbox** [comment]
Wrong mod page?
